# Generated by Django 4.0.2 on 2022-02-26 15:59

from django.db import migrations, models
import rest.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_member_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=rest.fields.FormattedField(default=None, max_length=64, null=True),
        ),
    ]
